# The Settings Object

The main purpose of Settings objects is managing attributes easily. 
A settings object can be initialized via a dictionary or a .yaml config file. 
All attributes are transformed to class attributes. 

In [1]:
# We import the settings class from the Settings module
from calibpy.Settings import Settings

settings = Settings()

we can populate the Settings instance from a dictionary

In [2]:
settings.from_params({
    "my_attr": 0,
    "my_other_attr": True
})
# this Settings object should now be populated
print(settings)

Settings Attributes:
	my_attr: 0
	my_other_attr: True



and we should be able to access the attributes directly from the object

In [3]:
print("my_attr =", settings.my_attr)
print("my_other_attr =", settings.my_other_attr)

my_attr = 0
my_other_attr = True


You can ensure that attributes are really available and have a specific type. 
This is useful when loading from .yaml to ensure your workflow has all fields 
expected as well as the correct input types.

In [4]:
print(settings.ensure("my_attr", int))
print(settings.ensure("my_other_attr", bool))

# you can be brutal and throw an Exception if the check fails 
try:
    print(settings.ensure("my_third_attr", float))
except Exception as e:
    print(e)

# or by setting throw_error=False, just return False in case
print(settings.ensure("my_third_attr", float, throw_error=False))

True
True
Missing Settings Entry [{key}] Exception!
False


Using save and load you can store the object and reload it as .yaml file

In [5]:
settings.save(save_dir="my/save/dir", filename="my_settings")
settings.from_config(config_filename="my/save/dir/my_settings.yaml")

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'my\\save\\dir'

# The Camera Object

The camera class is also mainly a data container storing all essential camera information. 
It inherits from a class called Serializer which makes it possible to easily access, write 
and load its data.

In [ ]:
import numpy as np
from calibpy.Camera import Camera
cam = Camera()

# using quick_init we can 
# init an example camera
cam.quick_init()
print(cam)

print("cam.f_px =", cam.f_px)
print("cam.fx =", cam.fx)
print("cam.fy =", cam.fy)

Camera:
-----------------------------------
 - name | <class 'str'>:
	Default Cam
 - f_mm | <class 'int'>:
	50
 - sensor_size | <class 'tuple'>:
	(20.25, 36.0)
 - image_size | <class 'tuple'>:
	(1080, 1920)
 - intrinsics | <class 'numpy.ndarray'>:
	[[2.66666667e+03 0.00000000e+00 9.60000000e+02]
 [0.00000000e+00 2.66666667e+03 5.40000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
 - distortion | <class 'numpy.ndarray'>:
	[[0. 0. 0. 0. 0.]]
 - RT | <class 'numpy.ndarray'>:
	[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 - RTb | <class 'numpy.ndarray'>:
	[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

cam.f_px = 2666.6666666666665
cam.fx = 2666.6666666666665
cam.fy = 2666.6666666666665


 We can set camera properties manually using compute_intrinsics and set_distortion...

In [ ]:
cam = Camera(name="MyCam")
cam.compute_intrinsics(f_mm=16.0, sensor_size=(7.5, 10), image_size=(960, 1280))
cam.set_distortion(k1=0.01, k2=-0.02, p1=0.03, p2=0.04, k3=-0.05)
print(cam)
print("cam.f_px =", cam.f_px)
print("cam.fx =", cam.fx)
print("cam.fy =", cam.fy)

Camera:
-----------------------------------
 - name | <class 'str'>:
	MyCam
 - f_mm | <class 'float'>:
	16.0
 - sensor_size | <class 'NoneType'>:
	None
 - image_size | <class 'tuple'>:
	(960, 1280)
 - intrinsics | <class 'numpy.ndarray'>:
	[[2.048e+03 0.000e+00 6.400e+02]
 [0.000e+00 2.048e+03 4.800e+02]
 [0.000e+00 0.000e+00 1.000e+00]]
 - distortion | <class 'numpy.ndarray'>:
	[[ 0.01 -0.02  0.03  0.04 -0.05]]
 - RT | <class 'NoneType'>:
	None
 - RTb | <class 'NoneType'>:
	None

cam.f_px = 2048.0
cam.fx = 2048.0
cam.fy = 2048.0


... or individually like so, ...

In [ ]:
from calibpy.Camera import Camera
import numpy as np
cam = Camera(name="MyCam")
cam.f_mm=16.0
cam.sensor_size=(7.5, 10)
cam.image_size=(960, 1280)
cam.compute_intrinsics()
cam.distortion = np.array([[0.01,-0.02,0.03,0.04,0.05]])
print(cam)
print("cam.f_px =", cam.f_px)
print("cam.fx =", cam.fx)
print("cam.fy =", cam.fy)

Camera:
-----------------------------------
 - name | <class 'str'>:
	MyCam
 - f_mm | <class 'float'>:
	16.0
 - sensor_size | <class 'NoneType'>:
	None
 - image_size | <class 'tuple'>:
	(960, 1280)
 - intrinsics | <class 'numpy.ndarray'>:
	[[2.048e+03 0.000e+00 6.400e+02]
 [0.000e+00 2.048e+03 4.800e+02]
 [0.000e+00 0.000e+00 1.000e+00]]
 - distortion | <class 'numpy.ndarray'>:
	[[ 0.01 -0.02  0.03  0.04  0.05]]
 - RT | <class 'NoneType'>:
	None
 - RTb | <class 'NoneType'>:
	None

cam.f_px = 2048.0
cam.fx = 2048.0
cam.fy = 2048.0


... or we load from a dict or .yaml file

In [ ]:
cam = Camera(name="MyCam")
cam.fro

cam.f_px = 2048.0
cam.fx = 2048.0
cam.fy = 2048.0
